### ISSUE TITLE
可以考虑用maven或者gradle管理一下项目

### ISSUE THREAD

**Issue by cbdyzj** [Fireflyi/java-Capture#1]
- v站看到了，资瓷一下javafx
- 主要是加了**mvnw**可以方便不开ide编译：）
- 另外，既然上了java8怎么不用**lambda**呢？j8新特性可以省不少力气

**Comment by Fireflyi** [comment]
java7+fx的jdk也是可以运行的  防止有人没用8  用的7+fxjdk 所以没用8新特性
以后的项目就用maven了管理了
fx很有意思的可以去学习下
